import heroTyre from "@/assets/hero-tyre.jpg";
import heroBattery from "@/assets/hero-battery.jpg";
import workshop from "@/assets/workshop.jpg";
import showroomInterior from "@/assets/showroom-interior.jpg";

export const images = { heroTyre, heroBattery, workshop, showroomInterior };

export const inr = (value) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);

export const tyres = [
  {
    slug: "moon-grip-gt-205-55-r16",
    name: "MoonGrip GT",
    brand: "Moon Performance",
    size: "205/55 R16",
    price: 6490,
    mrp: 7990,
    rating: 4.8,
    reviews: 214,
    type: "Passenger",
    season: "All Season",
    warranty: "5 years",
    stock: 24,
    highlights: ["Silica tread compound", "Wet grip A rating", "Low rolling resistance"],
    description:
      "A performance touring tyre engineered for Indian highways — asymmetric tread blocks bite through monsoon water while the reinforced sidewall shrugs off pothole impacts.",
  },
  {
    slug: "eclipse-sport-225-45-r17",
    name: "Eclipse Sport",
    brand: "Moon Performance",
    size: "225/45 R17",
    price: 9250,
    mrp: 11400,
    rating: 4.9,
    reviews: 168,
    type: "Performance",
    season: "Summer",
    warranty: "4 years",
    stock: 12,
    highlights: ["Ultra high performance", "Reinforced shoulder", "Track ready"],
    description:
      "Built for drivers who read the road through their fingertips. Stiff shoulder blocks hold the line through fast corners without punishing the cabin.",
  },
  {
    slug: "terra-crawler-at-265-65-r17",
    name: "Terra Crawler A/T",
    brand: "Lunar Offroad",
    size: "265/65 R17",
    price: 14800,
    mrp: 17200,
    rating: 4.7,
    reviews: 96,
    type: "SUV / 4x4",
    season: "All Terrain",
    warranty: "6 years",
    stock: 8,
    highlights: ["3-ply sidewall", "Stone ejectors", "Mud & rock ready"],
    description:
      "An all-terrain workhorse for weekend expeditions and everyday city duty, with a quiet-on-tarmac tread void ratio.",
  },
  {
    slug: "city-glide-155-80-r13",
    name: "City Glide",
    brand: "Moon Essentials",
    size: "155/80 R13",
    price: 3190,
    mrp: 3890,
    rating: 4.5,
    reviews: 402,
    type: "Hatchback",
    season: "All Season",
    warranty: "5 years",
    stock: 60,
    highlights: ["Fuel saver", "Long tread life", "Quiet ride"],
    description:
      "The everyday commuter's tyre. Optimised for stop-start traffic with a compound that stays supple through summer heat.",
  },
  {
    slug: "monsoon-shield-195-65-r15",
    name: "Monsoon Shield",
    brand: "Moon Performance",
    size: "195/65 R15",
    price: 5890,
    mrp: 7100,
    rating: 4.8,
    reviews: 311,
    type: "Sedan",
    season: "Wet",
    warranty: "5 years",
    stock: 33,
    highlights: ["Four-channel drainage", "Aquaplaning resistant", "Wet braking A"],
    description:
      "Four wide circumferential grooves evacuate standing water fast, keeping the contact patch planted in the heaviest downpour.",
  },
  {
    slug: "voltura-ev-215-55-r17",
    name: "Voltura EV",
    brand: "Moon Electric",
    size: "215/55 R17",
    price: 11250,
    mrp: 13400,
    rating: 4.9,
    reviews: 74,
    type: "EV",
    season: "All Season",
    warranty: "5 years",
    stock: 18,
    highlights: ["Foam noise cancelling", "High load index", "Range optimised"],
    description:
      "Designed around electric torque and kerb weight — foam inserts kill cabin drone and the low-hysteresis compound protects your range.",
  },
  {
    slug: "haul-master-lt-215-75-r15",
    name: "Haul Master LT",
    brand: "Lunar Commercial",
    size: "215/75 R15",
    price: 8400,
    mrp: 9900,
    rating: 4.6,
    reviews: 58,
    type: "Commercial",
    season: "All Season",
    warranty: "4 years",
    stock: 21,
    highlights: ["Heavy load rated", "Retreadable casing", "Cut resistant"],
    description:
      "A light commercial tyre for fleets that run all day. The deep casing can be retreaded twice, cutting cost per kilometre.",
  },
  {
    slug: "moon-grip-gt-185-65-r15",
    name: "MoonGrip GT",
    brand: "Moon Performance",
    size: "185/65 R15",
    price: 5290,
    mrp: 6400,
    rating: 4.7,
    reviews: 188,
    type: "Passenger",
    season: "All Season",
    warranty: "5 years",
    stock: 40,
    highlights: ["Balanced comfort", "Even wear", "Silent ribs"],
    description:
      "The compact-sedan favourite. Continuous centre rib keeps the steering crisp at highway speed.",
  },
  {
    slug: "apex-track-r-245-40-r18",
    name: "Apex Track R",
    brand: "Moon Motorsport",
    size: "245/40 R18",
    price: 16900,
    mrp: 19800,
    rating: 5,
    reviews: 41,
    type: "Performance",
    season: "Summer",
    warranty: "2 years",
    stock: 6,
    highlights: ["Semi-slick", "Motorsport compound", "Rapid warm-up"],
    description:
      "A road-legal semi-slick for track day regulars. Comes up to temperature in a single flying lap.",
  },
  {
    slug: "rover-hp-235-60-r18",
    name: "Rover HP",
    brand: "Lunar Offroad",
    size: "235/60 R18",
    price: 13100,
    mrp: 15200,
    rating: 4.6,
    reviews: 129,
    type: "SUV / 4x4",
    season: "All Season",
    warranty: "5 years",
    stock: 15,
    highlights: ["Highway quiet", "SUV load rated", "Wet certified"],
    description:
      "Highway-terrain rubber for premium SUVs that spend most of their life on tarmac but still see the occasional gravel trail.",
  },
  {
    slug: "swift-eco-165-80-r14",
    name: "Swift Eco",
    brand: "Moon Essentials",
    size: "165/80 R14",
    price: 3890,
    mrp: 4600,
    rating: 4.4,
    reviews: 268,
    type: "Hatchback",
    season: "All Season",
    warranty: "5 years",
    stock: 52,
    highlights: ["Best mileage", "Budget champion", "Puncture resistant"],
    description:
      "Our best-selling budget tyre — low rolling resistance that pays for itself over 40,000 km.",
  },
  {
    slug: "night-runner-205-60-r16",
    name: "Night Runner",
    brand: "Moon Performance",
    size: "205/60 R16",
    price: 7150,
    mrp: 8600,
    rating: 4.8,
    reviews: 143,
    type: "Sedan",
    season: "All Season",
    warranty: "5 years",
    stock: 27,
    highlights: ["Run-flat option", "Sealant lined", "Comfort tuned"],
    description:
      "Self-sealing technology closes punctures up to 5 mm instantly, so a nail on a dark highway is no longer a crisis.",
  },
];

export const batteries = [
  {
    slug: "moon-volt-x-65ah",
    name: "MoonVolt X",
    brand: "Moon Power",
    capacity: "65 Ah",
    cca: "620 A",
    price: 7490,
    mrp: 8900,
    rating: 4.9,
    reviews: 187,
    type: "Car",
    warranty: "48 months",
    stock: 30,
    highlights: ["Maintenance free", "Deep cycle safe", "Fast recharge"],
    description:
      "Calcium-alloy grid battery with 48 months of cover — the default choice for mid-size sedans and compact SUVs.",
  },
  {
    slug: "eclipse-agm-70ah",
    name: "Eclipse AGM",
    brand: "Moon Power",
    capacity: "70 Ah",
    cca: "760 A",
    price: 13900,
    mrp: 16200,
    rating: 4.9,
    reviews: 92,
    type: "Start-Stop",
    warranty: "60 months",
    stock: 14,
    highlights: ["AGM technology", "Start-stop rated", "Vibration proof"],
    description:
      "Absorbent glass mat construction for cars with start-stop and heavy electrical loads. Three times the cycle life of flooded cells.",
  },
  {
    slug: "lunar-lite-35ah",
    name: "Lunar Lite",
    brand: "Moon Essentials",
    capacity: "35 Ah",
    cca: "300 A",
    price: 3690,
    mrp: 4500,
    rating: 4.5,
    reviews: 340,
    type: "Hatchback",
    warranty: "36 months",
    stock: 45,
    highlights: ["Compact fit", "Zero top-up", "Budget friendly"],
    description:
      "A lightweight, sealed unit sized for hatchbacks. Fit and forget for three full years.",
  },
  {
    slug: "titan-heavy-150ah",
    name: "Titan Heavy",
    brand: "Lunar Commercial",
    capacity: "150 Ah",
    cca: "1100 A",
    price: 18400,
    mrp: 21000,
    rating: 4.7,
    reviews: 63,
    type: "Truck",
    warranty: "36 months",
    stock: 9,
    highlights: ["Truck & bus rated", "Thick plates", "High cranking"],
    description:
      "Built for long-haul trucks and buses running heavy auxiliary loads through the night.",
  },
  {
    slug: "moon-ride-9ah",
    name: "MoonRide",
    brand: "Moon Power",
    capacity: "9 Ah",
    cca: "130 A",
    price: 1890,
    mrp: 2400,
    rating: 4.6,
    reviews: 512,
    type: "Two Wheeler",
    warranty: "30 months",
    stock: 80,
    highlights: ["Spill proof", "Bike & scooter", "Instant crank"],
    description:
      "Sealed VRLA battery for motorcycles and scooters — mounts in any orientation, no acid top-up ever.",
  },
  {
    slug: "solaris-inverter-220ah",
    name: "Solaris Inverter",
    brand: "Moon Power",
    capacity: "220 Ah",
    cca: "—",
    price: 22400,
    mrp: 25900,
    rating: 4.8,
    reviews: 118,
    type: "Inverter",
    warranty: "60 months",
    stock: 11,
    highlights: ["Tubular plates", "Solar compatible", "Long backup"],
    description:
      "Tall tubular inverter battery for home backup and rooftop solar, tolerant of deep discharge cycles.",
  },
  {
    slug: "voltura-lithium-50ah",
    name: "Voltura Lithium",
    brand: "Moon Electric",
    capacity: "50 Ah",
    cca: "700 A",
    price: 34900,
    mrp: 39900,
    rating: 5,
    reviews: 27,
    type: "Lithium",
    warranty: "72 months",
    stock: 5,
    highlights: ["LiFePO4 cells", "70% lighter", "Smart BMS"],
    description:
      "Lithium iron phosphate pack with Bluetooth BMS — track state of charge from your phone and save 12 kg over the nose.",
  },
  {
    slug: "moon-volt-x-45ah",
    name: "MoonVolt X",
    brand: "Moon Power",
    capacity: "45 Ah",
    cca: "440 A",
    price: 5490,
    mrp: 6600,
    rating: 4.7,
    reviews: 205,
    type: "Car",
    warranty: "48 months",
    stock: 36,
    highlights: ["Maintenance free", "Wide fitment", "Fast recharge"],
    description:
      "The compact sibling of our best seller, fitting the majority of Indian hatchbacks and compact sedans.",
  },
  {
    slug: "guardian-ups-42ah",
    name: "Guardian UPS",
    brand: "Moon Power",
    capacity: "42 Ah",
    cca: "—",
    price: 6900,
    mrp: 8200,
    rating: 4.4,
    reviews: 88,
    type: "Inverter",
    warranty: "24 months",
    stock: 22,
    highlights: ["SMF sealed", "Rack mountable", "Low self discharge"],
    description:
      "Sealed maintenance-free UPS battery for small offices and clinics that cannot afford a flicker.",
  },
  {
    slug: "terra-marine-100ah",
    name: "Terra Marine",
    brand: "Lunar Commercial",
    capacity: "100 Ah",
    cca: "800 A",
    price: 15600,
    mrp: 18000,
    rating: 4.6,
    reviews: 34,
    type: "Marine",
    warranty: "36 months",
    stock: 7,
    highlights: ["Corrosion sealed", "Dual purpose", "Deep cycle"],
    description:
      "Dual-purpose marine cell that both cranks the engine and runs house loads at anchor.",
  },
];

export const services = [
  {
    slug: "tyre-fitting",
    title: "Tyre Fitting & Balancing",
    price: "From ₹250 / wheel",
    duration: "30 min",
    icon: "Wrench",
    summary: "Touchless mounting on German machines with road-force balancing.",
    details: [
      "Touchless bead breaking protects alloy rims",
      "Road-force balancing to under 5 grams",
      "New valve and nitrogen fill included",
    ],
  },
  {
    slug: "wheel-alignment",
    title: "3D Wheel Alignment",
    price: "₹899",
    duration: "45 min",
    icon: "Crosshair",
    summary: "Camera-based 3D alignment with a printed before/after report.",
    details: [
      "Camber, caster and toe corrected to OEM spec",
      "Steering angle sensor recalibration",
      "Printed report handed over with the keys",
    ],
  },
  {
    slug: "battery-installation",
    title: "Battery Fitting at Home",
    price: "Free with purchase",
    duration: "20 min",
    icon: "BatteryCharging",
    summary: "Doorstep battery replacement anywhere in the city, free of charge.",
    details: [
      "Memory saver keeps your ECU settings",
      "Terminal cleaning and anti-corrosion coating",
      "Old battery bought back on the spot",
    ],
  },
  {
    slug: "puncture-repair",
    title: "Puncture & Sidewall Repair",
    price: "From ₹150",
    duration: "20 min",
    icon: "LifeBuoy",
    summary: "Mushroom-plug repairs that are permanent, not temporary.",
    details: [
      "Inside-out mushroom plug, not a string plug",
      "Full tyre inspection for hidden damage",
      "Rebalanced after every repair",
    ],
  },
  {
    slug: "roadside-assistance",
    title: "24×7 Roadside Assistance",
    price: "₹1,499 / year",
    duration: "45 min ETA",
    icon: "Siren",
    summary: "Jump starts, tyre changes and towing, round the clock.",
    details: [
      "Unlimited jump starts within city limits",
      "Flat tyre change at your location",
      "Towing up to 50 km included",
    ],
  },
  {
    slug: "nitrogen-inflation",
    title: "Nitrogen Inflation",
    price: "₹200 / set",
    duration: "15 min",
    icon: "Wind",
    summary: "Stable pressure, cooler running, longer tread life.",
    details: [
      "99% pure nitrogen purge and fill",
      "Free top-ups for twelve months",
      "TPMS check included",
    ],
  },
  {
    slug: "battery-health-check",
    title: "Battery Health Diagnostics",
    price: "Free",
    duration: "10 min",
    icon: "Activity",
    summary: "Conductance testing of battery, alternator and starter draw.",
    details: [
      "State of health and state of charge printed",
      "Alternator ripple test",
      "Parasitic drain check",
    ],
  },
  {
    slug: "alloy-wheel-care",
    title: "Alloy Wheel Restoration",
    price: "From ₹1,800 / wheel",
    duration: "1 day",
    icon: "Sparkles",
    summary: "Kerb rash removed, diamond-cut or powder-coated finish.",
    details: [
      "CNC diamond cutting available",
      "Powder coat in any RAL shade",
      "Ceramic sealant on completion",
    ],
  },
];

export const brands = [
  "Moon Performance",
  "Lunar Offroad",
  "Moon Power",
  "Moon Electric",
  "Lunar Commercial",
  "Moon Essentials",
  "Moon Motorsport",
  "Apex Rubber",
];

export const testimonials = [
  {
    name: "Rohan Mehta",
    city: "Pune",
    car: "Skoda Octavia",
    quote:
      "Booked four MoonGrip GTs at 11 pm, fitted by 9 am next morning. The balancing report they hand over is something no other shop bothered with.",
    rating: 5,
  },
  {
    name: "Ananya Iyer",
    city: "Bengaluru",
    car: "Tata Nexon EV",
    quote:
      "The Voltura EV tyres genuinely dropped my cabin noise. Their team knew exactly what an EV needs — load index, foam, everything.",
    rating: 5,
  },
  {
    name: "Harpreet Singh",
    city: "Ludhiana",
    car: "Mahindra Thar",
    quote:
      "Terra Crawlers survived Spiti without a single sidewall cut. Free rotation every 10,000 km is a promise they actually keep.",
    rating: 5,
  },
  {
    name: "Fatima Sheikh",
    city: "Hyderabad",
    car: "Honda City",
    quote:
      "Battery died in an office basement. Their van reached in 38 minutes, fitted a MoonVolt X and took the old one away.",
    rating: 5,
  },
  {
    name: "Vikram Rao",
    city: "Chennai",
    car: "BMW 330i",
    quote:
      "Touchless mounting on my 18-inch alloys, not a mark anywhere. Worth every rupee over the cheap shop down the road.",
    rating: 5,
  },
  {
    name: "Neha Kulkarni",
    city: "Mumbai",
    car: "Maruti Baleno",
    quote:
      "Transparent pricing, GST invoice, EMI on the spot. Felt like a showroom, not a garage.",
    rating: 4,
  },
];

export const posts = [
  {
    slug: "how-to-read-tyre-sidewall",
    title: "How to read your tyre sidewall in 60 seconds",
    category: "Guides",
    date: "12 July 2026",
    readTime: "6 min",
    excerpt:
      "205/55 R16 91V looks like a serial number, but every character tells you something about how your car behaves.",
    body: [
      "The three numbers before the slash are the section width in millimetres — the widest point of the inflated tyre. Wider is not automatically better; it costs fuel and tramlines on rutted roads.",
      "The two digits after the slash are the aspect ratio: sidewall height as a percentage of width. A 55 profile on a 205 section means a 112 mm sidewall. Lower profiles sharpen steering and punish your spine.",
      "R means radial construction, and the number after it is the rim diameter in inches. Get this wrong and the tyre simply will not mount.",
      "The final pair is load index and speed rating. 91V means 615 kg per tyre at up to 240 km/h. Never fit below your manufacturer's placard value, which lives inside the driver's door jamb.",
      "Finally, hunt for the four-digit DOT week code. 3625 means the thirty-sixth week of 2025. Rubber ages even unused — we never sell stock older than six months.",
    ],
  },
  {
    slug: "monsoon-tyre-checklist",
    title: "The monsoon checklist every Indian driver skips",
    category: "Safety",
    date: "28 June 2026",
    readTime: "5 min",
    excerpt:
      "Aquaplaning starts at 3 mm of tread depth, not at the legal 1.6 mm limit. Here's the pre-monsoon routine we run on every car.",
    body: [
      "Tread depth first. Slot a ten-rupee coin into the main groove — if the outer rim of the coin disappears you still have depth, if it does not, you are hydroplaning waiting to happen.",
      "Check pressure cold, every fortnight. An underinflated tyre folds at the shoulder and lifts the centre of the contact patch clean off the road.",
      "Rotate front to back. Front tyres on a front-drive car wear roughly twice as fast, and mismatched grip front to rear is how a car snaps into a spin.",
      "Inspect for cuts and bulges after every pothole season. A sidewall bulge is an internal cord failure and is not repairable at any price.",
      "Finally, get the alignment checked. Monsoon potholes knock toe angles out, and a car pulling left in the dry will pull hard in the wet.",
    ],
  },
  {
    slug: "car-battery-lifespan-india",
    title: "Why car batteries die faster in India",
    category: "Batteries",
    date: "14 June 2026",
    readTime: "7 min",
    excerpt:
      "A battery rated for five years in Europe often gives three here. Heat, not cold, is the real killer.",
    body: [
      "Lead-acid chemistry ages twice as fast for every 10°C above 25°C. A bonnet bay at 55°C on an Ahmedabad afternoon is a slow cooking pot.",
      "Short city trips compound the problem. Starting the engine costs the battery a large slug of charge that a fifteen-minute crawl never fully replaces.",
      "Vibration from broken roads shakes active material off the plates. This is why we insist on a properly torqued hold-down clamp on every fitment.",
      "Aftermarket accessories — dashcams, subwoofers, ambient lighting — draw current with the ignition off. We measure parasitic drain free of charge on any car.",
      "The fix is not a bigger battery, it is the right one: calcium alloy or AGM, correctly sized, clamped down, and tested twice a year.",
    ],
  },
  {
    slug: "ev-tyres-different",
    title: "EV tyres are genuinely different — here's why",
    category: "Electric",
    date: "2 June 2026",
    readTime: "6 min",
    excerpt:
      "Instant torque, 300 kg of extra kerb weight and a silent cabin change every requirement in the specification sheet.",
    body: [
      "Electric cars are heavy. Battery packs add 250 to 400 kg, which means the load index on an EV tyre runs one or two steps higher than the equivalent petrol car.",
      "Torque arrives instantly and completely. Tread compounds must resist shear that a combustion engine only reaches at full throttle.",
      "With no engine noise to mask it, road roar dominates the cabin. Foam inserts bonded inside the tyre absorb the resonant frequency and cut perceived noise noticeably.",
      "Rolling resistance is range. A low-hysteresis compound can recover five to eight percent of driving range compared to a conventional tyre.",
      "We stock the Voltura EV line precisely for this, and we will never sell you a standard tyre for an electric car just because it fits.",
    ],
  },
  {
    slug: "wheel-alignment-symptoms",
    title: "Five signs your alignment is gone",
    category: "Guides",
    date: "20 May 2026",
    readTime: "4 min",
    excerpt:
      "Bad alignment quietly eats a set of tyres in 8,000 km. These are the tells you can spot from the driver's seat.",
    body: [
      "The steering wheel sits crooked while the car travels straight. That is toe or a bent steering arm, and it never fixes itself.",
      "The car drifts to one side on a flat, camber-free road when you briefly relax your grip.",
      "Feathered tread edges — run your palm across the tread and feel for a sawtooth. Sharp one way, smooth the other means excess toe.",
      "Uneven inner or outer shoulder wear points to camber error, common after kerb strikes.",
      "Vibration through the wheel at 70 to 90 km/h usually means balancing, but persistent vibration after balancing points at alignment or a bent rim.",
    ],
  },
  {
    slug: "nitrogen-vs-air",
    title: "Nitrogen versus air: marketing or measurable?",
    category: "Explainers",
    date: "5 May 2026",
    readTime: "5 min",
    excerpt:
      "We ran both across a fleet of forty cars for a year. The results are less dramatic than the posters claim — but not zero.",
    body: [
      "Air is already 78 percent nitrogen, so the marginal gain from a 99 percent fill is small. Anyone claiming a transformation is selling you something.",
      "The real benefit is moisture. Compressed air carries water vapour that expands unpredictably with heat; dry nitrogen does not.",
      "Across our fleet test, nitrogen-filled tyres lost pressure roughly 40 percent slower over twelve months.",
      "Slower pressure loss means fewer weeks driving underinflated, which is where the fuel and tread-life savings actually come from.",
      "Our honest verdict: worth ₹200 if you check your pressures rarely. Worth nothing if you check them every fortnight.",
    ],
  },
];

export const faqs = [
  {
    q: "Do you fit tyres and batteries at my home?",
    a: "Yes. Battery fitting at your home or office is free anywhere within city limits when you buy from us. Tyre fitting is a workshop job because balancing needs a calibrated machine, but we run free pickup and drop for orders of four tyres.",
  },
  {
    q: "What payment methods will you accept?",
    a: "UPI, all major credit and debit cards, net banking, and no-cost EMI on purchases above ₹10,000. Cash and card on delivery are also available. The payment gateway is being connected next — checkout currently records your order and our team confirms by phone.",
  },
  {
    q: "How old is the stock you sell?",
    a: "We never sell a tyre manufactured more than six months ago, and never a battery older than three months. The DOT week code is printed on your invoice so you can verify it yourself.",
  },
  {
    q: "Is the warranty handled by you or the manufacturer?",
    a: "Both. Manufacturer warranty applies as printed, and we add our own workmanship guarantee on every fitment. Claims are processed at our counter — you never have to chase a brand office.",
  },
  {
    q: "Do you buy back old batteries?",
    a: "Yes, at live scrap rates, adjusted directly against your new battery bill. We are a registered handler and dispose of every unit through an authorised recycler.",
  },
  {
    q: "Can I book a slot instead of waiting?",
    a: "Absolutely. Use the booking page to reserve a bay. Booked cars go straight onto the lift — average turnaround is 35 minutes for a full set of four.",
  },
  {
    q: "What does the free rotation programme include?",
    a: "Every set of four bought from us includes rotation and pressure checks every 10,000 km for the life of the tread, at no cost, at any of our branches.",
  },
  {
    q: "Do you handle commercial fleets?",
    a: "We run dedicated fleet accounts with consolidated monthly invoicing, on-site service vans and priority stock holding. Contact the franchise desk to set one up.",
  },
];

export const locations = [
  {
    city: "Mumbai",
    branch: "Andheri East Flagship",
    address: "Plot 42, MIDC Road No. 7, Andheri East, Mumbai 400093",
    phone: "+91 98200 41001",
    hours: "8:00 AM – 10:00 PM, all days",
    bays: 8,
  },
  {
    city: "Pune",
    branch: "Kharadi Service Hub",
    address: "Survey 61, Nagar Road, Kharadi, Pune 411014",
    phone: "+91 98220 41002",
    hours: "8:30 AM – 9:30 PM, all days",
    bays: 6,
  },
  {
    city: "Bengaluru",
    branch: "Whitefield Centre",
    address: "144, ITPL Main Road, Whitefield, Bengaluru 560066",
    phone: "+91 98450 41003",
    hours: "8:00 AM – 10:00 PM, all days",
    bays: 7,
  },
  {
    city: "Delhi NCR",
    branch: "Gurugram Sector 44",
    address: "Unit 9, Sector 44 Market, Gurugram 122003",
    phone: "+91 98110 41004",
    hours: "9:00 AM – 9:00 PM, all days",
    bays: 5,
  },
  {
    city: "Hyderabad",
    branch: "Gachibowli Express",
    address: "Plot 3, Financial District Road, Gachibowli, Hyderabad 500032",
    phone: "+91 90000 41005",
    hours: "8:30 AM – 9:30 PM, all days",
    bays: 4,
  },
  {
    city: "Chennai",
    branch: "OMR Perungudi",
    address: "221, Old Mahabalipuram Road, Perungudi, Chennai 600096",
    phone: "+91 90030 41006",
    hours: "8:30 AM – 9:00 PM, all days",
    bays: 5,
  },
];

export const stats = [
  { value: "1.2L+", label: "Wheels fitted" },
  { value: "27", label: "Years on the road" },
  { value: "6", label: "Cities served" },
  { value: "4.9", label: "Average rating" },
];

export const allProducts = [
  ...tyres.map((t) => ({ ...t, kind: "tyre" })),
  ...batteries.map((b) => ({ ...b, kind: "battery" })),
];

export const findProduct = (kind, slug) =>
  allProducts.find((p) => p.kind === kind && p.slug === slug);